### ISSUE TITLE
Docstring Issue: function_filter instead of class_filter

### ISSUE THREAD

**Issue by arosen93** [materialsproject/jobflow#110]
The codeblock below describes `update_maker_kwargs`, which has a `class_filter` but not a `function_filter` kwarg. I think this just needs a find+replace on `function_filter`.

https://github.com/materialsproject/jobflow/blob/fbd5868394c6f4f6b4f2e0ccf4b7ff7d21fe7258/src/jobflow/core/flow.py#L388-L419

**Comment by utf** [comment]
Closed with #111
