### ISSUE TITLE
BUG: Partial string match on name_filter

### ISSUE THREAD

**Issue by arosen93** [materialsproject/jobflow#114]
If I'm understanding it correctly, in the codeblock below, it seems as if a partial string match is done for the `name_filter`. For instance, if the `job` name is `adder` and the `name_filter=ad`, the kwargs will still be updated despite there not being a perfect string match. If this the desired behavior, then I think the documentation should be updated; otherwise, the behavior should be changed to `and name_filter != self.name`.

https://github.com/materialsproject/jobflow/blob/fbd5868394c6f4f6b4f2e0ccf4b7ff7d21fe7258/src/jobflow/core/job.py#L654-L659

**Comment by utf** [comment]
Partial string matching is supposed to be supported so I updated the docstrings. However, if full matching is important, I would be happy to support that using a special string (e.g., if the name filter starts and ends with "!!" or something like that). Happy to accept a PR if this is something you need.
