### ISSUE TITLE
Feature Suggestion: Updating the metadata of each job in a flow

### ISSUE THREAD

**Issue by arosen93** [materialsproject/jobflow#115]
Previously, you had shared with me this simple function to update a `Flow`'s metadata. I think it's so useful in fact that something analogous to it should be a part of the standard `jobflow` library, similar to how we have `update_kwargs` for a `Flow`. This is just to document it. The original discussion was at https://github.com/materialsproject/jobflow/issues/78#issuecomment-1004706355.

```python
def update_metadata(flow, metadata_updates):
    for job in flow.jobs:
        if isinstance(job, Flow):
            update_metadata(job, metadata_updates)
        else:
            job.metadata.update(metadata_updates)
```

**Comment by utf** [comment]
Hi @arosen93, I fixed this in #133.

Lets say you create a flow as follows:

```python
from jobflow import job, Flow

@job
def add(a, b):
   return a + b

add_job1 = add(5, 6)
add_job2 = add(6, 7)
flow = Flow([add_job1, add_job2])
```

The ``metadata`` of both jobs can be updated as:

```python
flow.update_metadata({"tag": "addition_job"})
```

The `update_metadata` function also supports a name filter, function filter, and dict mod updates.
