### ISSUE TITLE
Enhancement: Set metadata in Maker

### ISSUE THREAD

**Issue by gpetretto** [materialsproject/jobflow#193]
Currently it is possible to use the `update_metadata` method to set the metadata in Jobs and Flows. However, a Job can use a Maker to generate new Jobs/Flows at runtime . If I am not wrong there is no way for a user to easily set the metadata for the dynamically generated Jobs. 

I though it would be interesting to start a discussion about introducing a standardized way to deal with such a use case.  
An option could be to add a `metadata` attribute to the Maker base class and suggest that subclasses implementing the `make` method use it to call the update_metadata if they return a new Flow, while the `make` methods that are decorated with `@job` can automatically set the metadata. 

Do you think this may be an interesting feature? And does anybody have a better idea about how to implement it?

**Comment by utf** [comment]
There is some support for setting the metadata of dynamically created jobs. Specially, if you set the metadata of job that replaces itself with a new flow/job, the new flow/job will inherit the metadata of the original job. Whether this approach is flexible enough I'm not sure. Can you think of a situation where the current approach doesn't work but where your suggestion would work?

> suggest that subclasses implementing the make method use it to call the update_metadata if they return a new Flow

I've considered doing something like this before too. I'm a bit worried as it relies on people to actually implement this, and I'm sure many people will forget. Another approach could be to add a decorator that does this automatically, which potentially has a slightly lower barrier to people implementing it.

However, I think this raises a broader worry I have about controlling the settings of dynamic workflows. For example, you might want to have finer control over the job config of dynamically created jobs. The current approach is the same as for metadata (the config just gets passed down to dynamic jobs) but this might not be flexible enough.

**Comment by gpetretto** [comment]
Thanks for looking into this.

Consider the following example 

```python
@job
def number(n):
    return n


@job
def use_maker_job(maker):
    flow = maker.make()
    return Response(replace=flow)


@dataclass
class TestMaker(Maker):
    def make(self):
        j1 = number(1)
        j2 = number(2)
        return Flow([j1, j2], output=[j1.output, j2.output])

job = use_maker_job(TestMaker())
job.update_metadata({"test_meta": "test"})

run_locally(job)
```

This creates 4 entries in the DB, 1 for the initial job, two for the `number` jobs and one for the "replacement" job. Out of these only the first and last have the metadata set.  The same will happen for an addition/detour.
It would not be impossible to retrieve the other two from the DB. It should be enough to first fetch the last one and then use the hosts ids to find the others. But it could be interesting to have the option to directly search for those two. 

In a potential implementation the example could look like this:

```python
@dataclass
class TestMaker(Maker):

    @set_metadata
    def make(self):
        j1 = number(1)
        j2 = number(2)
        return Flow([j1, j2], output=[j1.output, j2.output])

maker = TestMaker()
maker.update_metadata({"test_meta_2": "from_maker"})
job = use_maker_job(maker)
job.update_metadata({"test_meta": "test"})
```

and have the specific metadata for the two middle jobs. 

However, I had the same concerns about leaving this as the resposibility of the developer. If the `@set_metadata` decorator is not added a user might be tricked into thinking that some metadata will be set, while it actually won't. And it would be relatively easy for a developer to forget it.

I did not think about the config, but indeed it might be useful to tune them as well. I suppose that if we can find a decent solution the same approach could be used for both metadata and config.

Some alternatives I had though about, but with their potential drawbacks:

- The metadata of a Job that returns a replace/addition/detour are always copied in all the added jobs. (easy to do, but limits the amount of metadata that can be set. Less useful for the config?)
- Just advise that if a Job uses replace/addition/detour in the respose should preferably expose a `generated_metadata` (or maybe a better name...) to allow the user to set those data. It could be used as a standard convention in atomate2 for example. (Still relies on the developers and adds a lot of boilerplate code)
- Same as the initial suggestion, but subclasses of Maker will not implement `make()`, but a `_make()` method, with the `make` being in the base class, calling the `_make` but retaining the full control of what is returned (breaks backward compatibility and I did not think this thorough in details, so maybe some other issues are present)

**Comment by utf** [comment]
Thanks for the code examples. I'd forgotten that the metadata/config wasn't applied to all jobs in the flow, just the last one. This is a difficult problem to solve and I'm not sure there is an easy solution. 

> The metadata of a Job that returns a replace/addition/detour are always copied in all the added jobs.

This would be the easiest and could also be applied to the config I think. However, one example where this approach would fall short:

Lets say I have a dynamic workflow that runs AMSET if the there are no imaginary modes in the phonon band structure. So you supply an AMSET maker that is dynamically called later on. This Maker submits a mixture of VASP and AMSET jobs. Therefore, the AMSET job doesn't exist when you submit the flow. AMSET only runs on a single node, whereas the VASP calculations will run on say 4, so you'd need to update the config for that one specific job. The above proposal doesn't support this.

> Just advise that if a Job uses replace/addition/detour in the response should preferably expose a generated_metadata

As you mention this would result in a lot of boilerplate and might not get implemented.

> Same as the initial suggestion, but subclasses of Maker will not implement make(), but a _make() method

This is also something I've thought about. It could work but would be  a bit messy and would potentially introduce a difference in the api for Flow Makers and Job Makers. Ultimately this would provide a lot of flexibility. However, I'm not sure how conflicts could be resolved. E.g., inner flow maker has one metadata set and an outer flow maker has another metadata set. Which ultimately gets applied to the job. This isn't a dealbreaker though.

### Delayed updates

One more suggestion to consider: Could this be achieved by delayed updates. E.g., when you run an update function (`update_config`, `update_metadata`, etc) on a job or flow, the update type (config/metadata) and arguments get stored somewhere in the job (e.g., a new attribute called `dynamic_updates`). Now, if the job returns a dynamic action (response/addition/etc) then the updates also get applied to the dynamically created jobs. Ideally there would be an option in the JobConfig to toggle this.

I think this would solve the issue I identified above for the amset case. E.g. (rough code)

```
# VaspAmsetMaker submits a mixture of VASP and AMSET jobs
full_amset_maker = VaspAmsetMaker()

# AmsetMaker runs amset specifically
full_amset_maker.update_config({"manager_config.fworker": "amset_node"}, class_filter=AmsetMaker)

flow = DelayedMaker(full_amset_maker)
```

While writing this I realised that `update_config` doesn't actually exist on the Makers yet, but this could easily be added in.

Does this new proposal make sense? And do you foresee any downsides?

**Comment by gpetretto** [comment]
The delayed updates is definitely an interesting proposal. Just to be sure, I suppose this should work even for nested Makers. Consider for example the VASP `PhononMaker` being developed. It contains a `run_phonon_displacements` job that calls another Maker (`PhononDisplacementMaker`) at runtime. 

Using an example similar to yours, I would expect that this should reach the Jobs generated by the `PhononDisplacementMaker`. Right?

```python
full_phonon_maker = PhononMaker()

job = use_maker_job(full_phonon_maker)

job.update_config({...}, name_filter="phonon static")
```

One potential downside would be that selecting the right subset of jobs just by name could be tricky for complicated workflows, however I don't think there would be any easy solution for such cases.

**Comment by utf** [comment]
> Using an example similar to yours, I would expect that this should reach the Jobs generated by the PhononDisplacementMaker. Right?

Yes absolutely! That's exactly what I had in mind. 

> One potential downside would be that selecting the right subset of jobs just by name could be tricky for complicated workflows, however I don't think there would be any easy solution for such cases.

I agree. However, this seems extremely difficult to handle for all of the proposed solutions. 

Do you think we should go ahead with this solution?

**Comment by gpetretto** [comment]
> Do you think we should go ahead with this solution?

I think it would be good. Should I prepare a first draft of the implementation? Or would you prefer to do it yourself?

**Comment by utf** [comment]
If you'd be happy to do it, then that would be awesome. I'm not sure when I'll next have the chance.

Thanks!
