### ISSUE TITLE
BUG: matplotlib missing form requirements.txt dependencies list?

### ISSUE THREAD

**Issue by xperrylinn** [materialsproject/jobflow#276]
**Describe the bug**
Running the code [5 min quickstart](https://materialsproject.github.io/jobflow/tutorials/1-quickstart.html) after creating a new conda environment (Python 3.10) and pip installing `jobflow`, I got `ModuleNotFoundError` for `matplotlib`.  I looked at the `requirements.txt` and noticed no mention of `matplotlib`. Should it be listed as a dependency? Thank you!

**To Reproduce**
1. Create a fresh conda environment, Python 3.10
2. Activate new environment
3. `conda install pip`
4. `pip install jobflow`
5. Run quickstart code `flow.draw_graph(figsize=(3, 3)).show()` 
Provide any example files that are needed to reproduce the error,
especially if the bug pertains to parsing of a file.

**Expected behavior**

**Screenshots**

**Comment by davidwaroquiers** [comment]
Hello,

This is not a bug, in the installation guide, you can see that visualization can be installed using:

`pip install jobflow[vis]`

See here: [https://materialsproject.github.io/jobflow/install.html#pip](https://materialsproject.github.io/jobflow/install.html#pip)

One could possibly make a more verbose error message mentioning the above.

Best,

**Comment by utf** [comment]
Thanks for noticing this. I added a line to the tutorial about installing jobflow with the visualisation dependencies.
