### ISSUE TITLE
[Possible Bug] Settings loaded before test_settings_init

### ISSUE THREAD

**Issue by jmmshn** [materialsproject/jobflow#305]
I'm running into errors on my local testing due to the fact that the 
```
        # pick the local configuration
        os.environ["JOBFLOW_CONFIG_FILE"] = "/some/not/existing/path"
```
Line from the block below is not respected.
https://github.com/materialsproject/jobflow/blob/1a876e01960f9c0e170662a5011251b56c57b11a/tests/test_settings.py#L8-L13

I'm guessing the settings are loaded globally somewhere by accident?  @utf Please let me know if there is any information about this.

**Comment by utf** [comment]
I think it might be because of this line which was recently added in #293.

Can you move this import into the function which uses it.

Maybe that will fix it?

**Comment by jmmshn** [comment]
oh yeah.  missed that fixed in a new PR.  might need a linting rule for this.

**Comment by utf** [comment]
Cheers.
