### ISSUE TITLE
Recommendation: Open up Discussions on GitHub

### ISSUE THREAD

**Issue by arosen93** [materialsproject/jobflow#340]
Currently, the README says to refer to the matsci.org Fireworks page for Q&A. However, I personally think it would be better to open up the Discussions tab on the GitHub repo.

My main reason for this is that most people aren't actively monitoring the matsci.org forum, especially contributors. The matsci.org forum works best when there are dedicated staff reading it and responding to all issues, but that doesn't seem like the case here. Opening up the Discussions board on the repo would make it much easier for people other than the maintainers (e.g. me!) to spot questions and answer them. I have the same recommendation for Atomate2.

**Comment by utf** [comment]
I'm potentially open to this but does differ from the recent discussions in the MP foundation meetings. Any thoughts @rkingsbury, @JaGeo, @munrojm, @janosh ?

**Comment by arosen93** [comment]
Ah, missed that prior discussion! Good to know 👍

**Comment by janosh** [comment]
> but it does differ from the recent discussions in the MP foundation meetings.

It does? Last I heard was MPF agreed every repo should have its own discussion tab. Maybe I only what I like to hear. 😆 
Either way, I'm all for @arosen93's suggestion.

It's a single button click to convert an issue into a discussion and vice versa. I expect issues that really should have been discussions and migrated over by us will be the initial population of the new discussions tab until more people learn about it and go there naturally.

**Comment by JaGeo** [comment]
I think we somehow changed our mind in this regard. In March, we decided that we wouldn't want individual discussion boards. In May, we added it as an option. See here https://github.com/materialsproject/foundation/pull/4/files . It's mostly up to you, @utf, I think.

**Comment by rkingsbury** [comment]
Yes, although I missed the May MPSF meeting, if I'm reading the current state of the proposal, I see:

> * Optional: Have a "Dev Project" discussion board in every single MP repo with a pinned comment at the top linking the "MP Dev Guide"

So I think if you want to turn on discussion for atomate2 @utf , that is consistent with the collaborative vision we developed. Once the Developer Guide is ready, if you could just make sure to prominently link to it in your README and/or a pinned discussion or something that would be great.

**Comment by utf** [comment]
Great, thanks for the thoughts! I'll open up the discussion board!

**Comment by utf** [comment]
Done!
