### ISSUE TITLE
Logo needed!

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [materialsproject/jobflow#357]
Like in https://github.com/materialsproject/atomate2/issues/372, Jobflow needs a logo at some point! Currently facing this when preparing a presentation :)

**Comment by davidwaroquiers** [comment]
Hi @arosen93 

Working on this ;-) Should come soon hopefully

**Comment by arosen93** [comment]
Oooooooh! Looking forward to it!!

**Comment by davidwaroquiers** [comment]
> Oooooooh! Looking forward to it!!

Just for inforation, our graphist will work on this next week.

**Comment by JaGeo** [comment]
Very cool! 😃

**Comment by davidwaroquiers** [comment]
Here are two propositions from our graphist. Feel free to comment/criticize.
[Propositions Jobflow.pdf](https://github.com/materialsproject/jobflow/files/12195805/Propositions.Jobflow.pdf)

The translation of the explanations are:
First one: "A concept of multiple JOBS, with different thicknesses to symbolize hierarchy and a gradient in colors to represent a notion of movement. The concept of 1 FLOW for multiple JOBS."

Second one: "A notion of arrows to symbolize direction, and...hop, sent into the flow!"

Personally I like more the first one even though I find the "JOB" word a little bit too small with respect to FLOW.


I also hereby mention @utf 's comments received by mail but feel free to add more of your thoughts ;)

**_Personally, I think I like the second one more. I agree that “job" is too small in the first one._**

**_My main comments on the second one would be:_**

- **_When scaled down it is a bit harder to read as the lines are very thin. Perhaps the lines could be made thicker._**
- **_I think the size of the arrow on the w is slightly too long._**
- **_There seems to be a very small floating black arrowhead. I’m guessing that shouldn’t be there._**

**Comment by arosen93** [comment]
I like the second one more as well. The first one is too busy visually, making it not really an effective logo in my opinion (in addition to the "job" being far too small).

The second one still gets across the idea of workflows and I think is much stronger. I agree with @utf's comments as well.

**Comment by JaGeo** [comment]
@davidwaroquiers I also prefer the 2nd one. I think it looks great. I also agree with @utf 's comments.

**Comment by davidwaroquiers** [comment]
Great, thx for your comments, I'll forward the comments on the second one to get an update.

**Comment by davidwaroquiers** [comment]
New version with the lines thicker. I like it better. If this one is ok for you I tell our graphist it's ok as it is. If you have other comments, feel free to provide any.
[Propositions Jobflow2.pdf](https://github.com/materialsproject/jobflow/files/12597496/Propositions.Jobflow2.pdf)

**Comment by davidwaroquiers** [comment]
@utf 
@Andrew-S-Rosen 
What do you think about the new version?

**Comment by utf** [comment]
I definitely prefer the newer version. Also tagging @computron for his thoughts.

**Comment by Andrew-S-Rosen** [comment]
The latter is more visible than the former. As a logo, it's fine. Although if I am to nitpick, there are a few oddities about it.

For instance, why is just the "w" in orange? Having the entire "flow" part of "Jobflow" be in orange seems like it would make more sense thematically.

Additionally, the vertically offset "f" and "l" is a bit confusing, visually. It's not clear to me why this was done. This might be a situation where if a vertical offset is desired, it should be on the "f" rather than the "l" to mark the distinction between "Job" and "flow" in "Jobflow."

**Comment by davidwaroquiers** [comment]
> The latter is better than the former since it is easier to see when printed or on screen. As a logo, it's fine. Although if I am to nitpick, there are a few oddities about it.
> 
> For instance, why is just the "w" in orange? Having the entire "flow" part of "Jobflow" be in orange seems like it would make more sense thematically.
> 
> Additionally, the vertically offset "f" and "l" is a bit confusing, visually. It's not clear to me why this was done. This might be a situation where if a vertical offset is desired, it should be on the "f" rather than the "l" to mark the distinction between "Job" and "flow" in "Jobflow."

Hi @Andrew-S-Rosen 

Thanks for the feedback! Indeed your remarks perfectly make sense! I will forward them to our graphist (actually, she also did the one for qtoolkit, maybe you saw it ? and I prefer that one).


Best,

**Comment by janosh** [comment]
Oh, didn't know there was already a jobflow logo issue. Came here to open one and suggest this logo. Tried to use similar colors as the suggested atomate2 logo in https://github.com/materialsproject/atomate2/issues/372 since the two codes are so closely related. Just a rough draft to float the idea.

I also really like the logo posted by @davidwaroquiers!

![jobflow](https://github.com/materialsproject/jobflow/assets/30958850/0650d187-8a42-4962-a95d-ff40354baf6b)

**Comment by davidwaroquiers** [comment]
I'm not good with colors but here is the same one changed with some colors similar to the one in atomate2.

![logo_jobflow_different_colors](https://github.com/materialsproject/jobflow/assets/3625296/b3cf7316-8c56-4d3c-aca5-e7b7d452272e)

**Comment by JaGeo** [comment]
I don't think we have decided on an atomate2 logo. I think there are some issues when it comes to how this logo was generated ;)....

**Comment by Andrew-S-Rosen** [comment]
Regardless, I like the new color scheme better!

**Comment by davidwaroquiers** [comment]
Another color scheme from our graphist (I like this one better):

![jobflow_logo](https://github.com/materialsproject/jobflow/assets/3625296/0b8ac98e-54b0-4057-acf8-ce94019c257e)
