### ISSUE TITLE
Flow + Job magic methods

### ISSUE THREAD

**Issue by janosh** [materialsproject/jobflow#368]
How come `Jobs` and `Flows` don't have 

- `__len__`
- `__getitem__`
- `__setitem__`
- `__iter__`
- `__repr__`

and friends?

Would be nice if `len(flow)` returned an `int` and `print(flow)` gives insightful output about containing each job's name etc.

```py
flow = MPMetaGGARelax().make(structure)

len(flow)
> TypeError: object of type 'Flow' has no len()
# expected 3

print(flow)
> <jobflow.core.flow.Flow object at 0x2c1386190>
# expected:
# MPMetaGGARelax flow consisting of
# 1. MP pre-relax
# 2. MP meta-GGA Relax
# 3. MP meta-GGA Static
```

**Comment by mkhorton** [comment]
How would `__len__` work for nested Flows, e.g. is `__len__` counting just `Job` or a mix of `Job` and `Flow`?

**Comment by janosh** [comment]
My opinion is it should return the top-level length of a `Flow` including both `Jobs` and `Flows`. E.g. [this example](https://github.com/materialsproject/jobflow/pull/369#issuecomment-1641064680) would return 3, not counting the jobs in subflows. That way, `__len__` is consistent with with the number of iterations in `__iter__`.

```py
from jobflow import Flow, Job


def add(a, b):
    return a + b

def get_test_job():
    return Job(add, function_args=(1, 2))

subflow1 = Flow([get_test_job()])
subflow2 = Flow([get_test_job(), get_test_job()])
subsubflow = Flow([get_test_job(), get_test_job()])
subflow3 = Flow([get_test_job(), get_test_job(), subsubflow])
print(Flow([subflow1, subflow2, subflow3]))
```
