### ISSUE TITLE
Which discussion forum are we using?

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [materialsproject/jobflow#414]
In the README, [there is a link](https://materialsproject.github.io/jobflow/contributing.html) to the FireWorks matsci.org page for the discussion forum, but we also have the Discussions tab opened here. Is the README link meant to be updated?

With an answer to the above question, we should also update the following text [in the docs](https://materialsproject.github.io/jobflow/contributing.html):

> jobflow is still in development, so at the moment we do not have a dedicated help forum. For the time being, please submit questions and bugs to the [GitHub issues page](https://github.com/materialsproject/jobflow/issues).

**Comment by utf** [comment]
Personally, I like GitHub discussions, so I would be happy to update the recommended place to post issues. This is also inline with the MP foundation decision: https://github.com/materialsproject/foundation/blob/main/decisions/0004-planning-of-developments.md

However, if we do that, we should probably close the matsci forum to avoid confusion. Pinging @mkhorton here.

**Comment by arosen93** [comment]
Would we need to close the forum since it's specifically labeled as being for fireworks?

**Comment by utf** [comment]
I was talking about this one: http://matsci.org/jobflow
