### ISSUE TITLE
JOSS Paper: Ensure code blocks are presented nicely

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [materialsproject/jobflow#453]
As shown in [the draft](https://github.com/openjournals/joss-reviews/issues/5951#issuecomment-1763288768) of the Jobflow paper, one of the codeblock examples runs between pages. This is visually undesirable. For the final version, we will want to make sure this is avoided, either by adjusting where we place the code-block or by making a static image of the code block with smaller linespacing than JOSS auto-generates from Markdown.

![image](https://github.com/materialsproject/jobflow/assets/8674072/2136719f-c63c-436a-bedd-c6dcc83358b1)

**Comment by JaGeo** [comment]
This can be closed then, right?

**Comment by Andrew-S-Rosen** [comment]
I didn't end up re-rendering it so am not sure if it still overflows. Either way, I wanted to change the 2 blank lines to 1 blank line regardless.

**Comment by utf** [comment]
[paper-6.pdf](https://github.com/materialsproject/jobflow/files/12914011/paper-6.pdf)


Here is the latest paper pdf.
