### ISSUE TITLE
FibonacciAdder example flow?

### ISSUE THREAD

**Issue by JaGeo** [materialsproject/jobflow#493]
I am currently wondering if one can easily recreate the FibonacciAdderTask example from Fireworks with jobflow. ( see here https://materialsproject.github.io/fireworks/guide_to_writing_firetasks.html). None of the examples that are currently provided would hint at this.

**Comment by utf** [comment]
Does this not do it: https://github.com/materialsproject/jobflow/blob/main/examples/fibonacci.py
________________________________
From: J. George ***@***.***>
Sent: Thursday, November 23, 2023 10:25:12 PM
To: materialsproject/jobflow ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [materialsproject/jobflow] Fibonacci example (Issue #493)


I am currently wondering if one can easily recreate the FibonacciAdderTask example from Fireworks with jobflow. ( see here https://materialsproject.github.io/fireworks/guide_to_writing_firetasks.html). None of the examples that are currently provided would hint at this.

**Comment by JaGeo** [comment]
Thanks! Yes, it does, of course. (Sorry, I am stupid) Maybe, we add it to the documentation as well ... (Meanwhile, I was also able to construct such an example myself and wanted to close the issue ...)
