### ISSUE TITLE
BUG: PyYAML is not installed with pip

### ISSUE THREAD

**Issue by arosen93** [materialsproject/jobflow#67]
**Describe the bug**
In a fresh conda environment with Python 3.8, doing `pip install jobflow` does not install `PyYAML`, so `import yaml` is not functional.

**Comment by utf** [comment]
Interesting. The pip installation seems to work in the test environment so I'm not sure why its not working in conda.

**Comment by utf** [comment]
Ah, PyYAML is in `requirements.txt` but not in setup.py. I'll fix now.
