### ISSUE TITLE
BUG: flow_to_workflow metadata tags not passed to Fireworks

### ISSUE THREAD

**Issue by arosen93** [materialsproject/jobflow#78]
**Describe the bug**
When using `flow_to_workflow` with tags specified like below
```python
from jobflow import Flow
from jobflow.managers.fireworks import flow_to_workflow

# jobs defined here
flow = Flow([job1, job2])
flow_to_workflow(flow, metadata={"tags": ["test_tag"]])
```
the resulting fireworks (jobs) do not appear to have any tag-based metadata associated with them. I haven't had time to dig into this just yet, but I will report back here with any further details and a fix hopefully in the near future.

**Comment by utf** [comment]
So the way you've used `flow_to_workflow` means that the metadata will get added to the Workflow object and not FireWorks objects. E.g. see: https://github.com/materialsproject/jobflow/blob/fb35f2d6e632ff4c47a430e1ce0deeabb8a66501/src/jobflow/managers/fireworks.py#L59

If you want Firework metadata you can just set the metadata of the job directly. 

I need to add a simpler way of updating metadata for all jobs. Currently, I'm using this function:

```
def update_metadata(flow, metadata_updates):
    for job in flow.jobs:
        if isinstance(job, Flow):
            update_metadata(job, metadata_updates)
        else:
            job.metadata.update(metadata_updates)
```

But ultimately, this will be easier with just a new function on the Job/Flow object itself.

**Comment by arosen93** [comment]
Thanks for the suggestions, as always! I had figured this might be the case. I wonder if it would be worthwhile to have the flow metadata passed down to the individual jobs. Perhaps that's not the best solution long-term though.

I'll update the job metadata directly for now.
