### ISSUE TITLE
BUG: dict object is not callable when run via FireWorks

### ISSUE THREAD

**Issue by arosen93** [materialsproject/jobflow#86]
I was trying to help @arepstein with launching his first jobflow, but it seems we've stumbled upon a FireWorks-related problem. In short, for any `Job` or `Flow` we launch as a firework, it gets added to the launchpad successfully but always fizzles due to the error below. I can confirm that the job runs successfully (and to completion) when done locally. I haven't had this issue in the past, so I'm not sure what version changes caused this new conflict.

Here is a minimal example:
```python
from jobflow import job
from jobflow.managers.local import run_locally
from jobflow.managers.fireworks import job_to_firework
from fireworks import LaunchPad


@job
def add(a, b):
    return a + b


job1 = add(1, 5)
# out = run_locally(job1)
wf = job_to_firework(job1)
lpad = LaunchPad.auto_load()
lpad.add_wf(wf)
```

Here is the traceback:

> "Traceback (most recent call last):\n  File \"/global/homes/r/rosen/software/miniconda/envs/rosen/lib/python3.8/site-packages/fireworks/core/rocket.py\", line 265, in run\n    m_action = t.run_task(my_spec)\n  File \"/global/homes/r/rosen/software/miniconda/envs/rosen/lib/python3.8/site-packages/jobflow/managers/fireworks.py\", line 177, in run_task\n    response = job.run(store=store)\n  File \"/global/homes/r/rosen/software/miniconda/envs/rosen/lib/python3.8/site-packages/jobflow/core/job.py\", line 524, in run\n    response = function(*self.function_args, **self.function_kwargs)\nTypeError: 'dict' object is not callable\n"

Version numbers are below: 
python == 3.8.12
jobflow == 0.1.6 (also tried `main`)
fireworks == 1.9.8
pymongo == 4.0.1

**Comment by utf** [comment]
This is because `add` is defined in the submission script only and is not an importable function when you launch the job. I.e., it isn't importable from anywhere.

**Comment by arosen93** [comment]
Oh jeeze, again. I'm sorry, @utf! Rookie mistake.

**Comment by arosen93** [comment]
To anyone that comes here, it's essentially the same issue as #72 -- just a different message in return. Make sure your modules are importable if using FireWorks because that's how it works!
