### ISSUE TITLE
Documentation: Dynamic workflows, FireWorks, Makers, and Updating Metadata

### ISSUE THREAD

**Issue by arosen93** [materialsproject/jobflow#90]
Currently, the Jobflow tutorials are missing some important concepts like dynamic workflows (with `Response`) and how to use Jobflow with FireWorks (although this is partially covered in the Atomate2 docs). 

I've been using dynamic workflows a lot lately, so I'm happy to contribute when I get the time. 

Edit: Forgot about Makers too.

**Comment by utf** [comment]
Good points! Any help with the documentation would be massively appreciated.

**Comment by Kokookster** [comment]
Hi! I'm also interested in a tutorial/working example about job flow+fireworks. There is actually a link to a tutorial on this page:
https://materialsproject.github.io/jobflow/
in the section "Five minutes quick start":
https://hackingmaterials.lbl.gov/jobflow/tutorials/6-fireworks.html
But the link seems to be broken. Any chance to restore this link?

**Comment by arosen93** [comment]
The documentation for that section hasn't been developed yet. I know this is a very old post, but I have not forgotten about it! It's still on my to-do list and will likely get to it sometime in May or so.

**Comment by arosen93** [comment]
Alright folks, it's only 1 yr 4 months since my original post, but I actually plan to get to it this now! Will try to open a PR by the end of this week.

**Comment by JaGeo** [comment]
Very much looking forward to it. Especially because of https://github.com/materialsproject/atomate2/issues/278
